name: sync_webdriver
version: 1.1.1
author: Marc Fisher II
description: Provides WebDriver bindings for Dart. These use the WebDriver JSON interface, and as such, require the use of the WebDriver remote server.
environment:
  sdk: '>=1.9.0-dev.2.2 <2.0.0'
dependencies:
  crypto: '>=0.9.0 <0.10.0'
  matcher: '>=0.11.3 <0.12.0'
  sync_socket:
    path: ../dart-sync-socket
dev_dependencies:
  path: '>=1.3.1 <2.0.0'
  unittest: '>=0.11.4 <0.12.0'
