name: sync_webdriver
author: Marc Fisher II
version: 1.0.0
description: Provides WebDriver bindings for Dart. These use the WebDriver JSON interface, and as such, require the use of the WebDriver remote server.
environment:
  sdk: '>=1.5.3 <2.0.0'
dependencies:
  collection: '>=0.9.4 <0.10.0'
  crypto: '>=0.9.0 <0.10.0'
  matcher: '>=0.11.1 <0.12.0'
  sync_socket:
    path: ../dart-sync-socket
dev_dependencies:
  path: '>=1.2.2 <2.0.0'
  unittest: '>=0.11.0+3 <0.12.0'

