name: sync_webdriver
version: 1.2.1
author: Google Inc.
description: >
  Provides WebDriver bindings for Dart. These use the WebDriver JSON interface,
  and as such, require the use of the WebDriver remote server.
homepage: https://github.com/google/dart-sync-webdriver
environment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  crypto: '^0.9.0'
  matcher: '^0.11.4+3'
  stack_trace: '^1.2.4'
  sync_socket: '^1.0.1'
dev_dependencies:
  path: '^1.3.3'
  unittest: '^0.11.5+4'
