name: sync_webdriver
author: Marc Fisher II
version: 0.0.7
description: Provides WebDriver bindings for Dart. These use the WebDriver JSON interface, and as such, require the use of the WebDriver remote server.
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  collection_helpers: '>=0.9.0 <0.10.0'
  crypto: '>=0.9.0 <0.10.0'
  sync_socket:
    path: ../dart-sync-socket
dev_dependencies:
  path: '>=0.9.0 <0.10.0'
  unittest: '>=0.9.0 <0.10.0'
